using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fly_System_DB_Generator.StaticData
{
    class ListOfAirlinesCompanies
    {
        public static string[] AirlineNames = new string[]
        {
            "BLUE AIR AIRLINE MANAGEMENT SOLUTIONS S.R.L.",
            "PREMIUM JET AG",
            "VIETNAM AIR SERVICE COMPANY",
            "AMADEUS IT GROUP SA",
            "SABRE ASIA PACIFIC PTE. LTD.",
            "RADIXX SOLUTIONS INTERNATIONAL, INC.",
            "Travelport International Operations Limited",
            "JSC SIRENA-TRAVEL",
            "DRF STIFTUNG LUFTRETTUNG GEM AG",
            "NetJets Aviation, Inc.",
            "SUTRA INC.",
            "JSC TRANSPORT AUTOMATED INFORMATION SYSTEMS - TAIS",
            "NAVITAIRE",
            "InteliSys Aviation Systems (2013)",
            "SABRE INC.",
            "ITA SOFTWARE INC.",
            "GALILEO INTERNATIONAL",
            "FLY BRANSON TRAVEL DBA BRANSON AIR EXPRESS",
            "Bird Information Systems Private Limited",
            "DYNAMIC AIRWAYS, LLC",
            "SMOKEY BAY AIR, INC.",
            "Afrinat International Airlines",
            "OPEN JOINT STOCK COMPANY ANGARA AIRLINES",
            "THALYS INTERNATIONAL",
            "STAR UP S.A.",
            "21 AIR LLC",
            "AIR BURKINA",
            "AEROLINEAS GALAPAGOS S.A. AEROGAL",
            "HELVETIC AIRWAYS AG",
            "TRANSPORTES AEREOS BOLIVIANOS",
            "Maya Island Air",
            "NEXTJET AB",
            "REDEMPTION INC.",
            "AIR PHILIPPINES CORPORATION",
            "Air Cargo Carriers, LLC.",
            "ATLANTIS EUROPEAN AIRWAYS",
            "TIMBIS AIR SERVICES",
            "SUN D'OR INTERNATIONAL AIRLINES",
            "AMTRAK",
            "WELCOME AIR LUFTFAHRT GMBH & CO KG",
            "PT. MY INDO AIRLINES",
            "PASSAREDO TRANSPORTES AEREOS S.A.",
            "BINTER CABO VERDE SOCIEDADE UNIPRESS S.A.",
            "AIR CHATHAMS LIMITED",
            "DOKASCH GMBH",
            "MULTI-AERO, INC. DBA AIR CHOICE ONE",
            "PACIFIC AIRWAYS INC.",
            "DRB-HICOM ASIA CARGO EXPRESS (DHACE) SDN BHD",
            "AIR INUIT LTD/LTEE",
            "Jubba Airways Limited",
            "JETSTAR ASIA AIRWAYS PTE LTD",
            "SILVER AIRWAYS CORP.",
            "AIR URGA",
            "AIR ARABIA MAROC",
            "TIARA AIR N.V. DBA TIARA AIR ARUBA",
            "AEROLOGIC GMBH",
            "CAIRE DBA AIR ANTILLES EXPRESS",
            "TARCO AIR",
            "SICHUAN AIRLINES CO. LTD.",
            "TNT AIRWAYS S.A.",
            "MALAWIAN AIRLINES",
            "PREMIER TRANS AIRE INC.",
            "BASEOPS INTERNATIONAL",
            "TRAVEL SERVICE POLSKA SP ZOO",
            "BOUTIQUE AIR, INC.",
            "AVIASTAR-TU CO.  AVIACOMPANY",
            "AEROVIAS DE INTEGRACION REGIONAL",
            "AIR SINAI",
            "STABO AIR LIMITED",
            "GAZPROMAVIA AVIATION COMPANY LTD.",
            "KENN BOREK AIR LTD.",
            "LINEAS AEREAS SURAMERICANAS S.A.",
            "LAN ARGENTINA S.A.",
            "AIR NORTH CHARTER AND TRAINING LTD.",
            "ABC AEROLINEAS S.A. DE C.V.",
            "Public Charters, Inc",
            "SAFI AIRWAYS LTD.",
            "SOLAR CARGO, C.A.",
            "Transwest Air Limited",
            "GERMANWINGS GMBH",
            "BV AIRWAYS DBA BVI AIRWAYS",
            "ALLIED AIR LTD.",
            "WARBELOW'S AIR VENTURES, INC.",
            "MERCURY AIR CARGO, INC.",
            "Airbus Transport International",
            "SA  AIRLINK",
            "ALPINE AVIATION INC.",
            "BASSAKA AIR LIMITED",
            "C.A.L. CARGO AIRLINES LTD.",
            "AEROLITORAL S.A. DE C.V.",
            "EAST COAST FLIGHT SERVICES, INC",
            "FLY ONE S.R.L.",
            "AEROCUAHONTE SA DE CV",
            "FIVE FOURTY AVIATION LIMITED",
            "Alsa Grupo SLU",
            "CEBU PACIFIC AIR",
            "HI FLY, S.A.",
            "MEDITERRANEAN AVIATION COMPANY LTD.",
            "FLY MONTSERRAT (MONTSERRAT AIRWAYS LTD)",
            "JOINT-STOCK COMPANY NORDAVIA - REGIONAL AIRLINES"
        };
    }
}
